<%@page contentType="text/html" pageEncoding="UTF-8"%><%@include file="includes/auth.jsp"%><% request.setAttribute("activePage","products"); request.setAttribute("pageTitle","Products"); %>
<!DOCTYPE html><html><head><title>Products</title><%@include file="includes/header.jsp"%></head><body><div class="app"><%@include file="includes/sidebar.jsp"%><main class="main"><%@include file="includes/topbar.jsp"%>
<div class="table-toolbar"><div class="table-search"><span>🔍</span><input type="text" placeholder="Search products by name..." oninput="filterTable('prod-table',this.value)"></div><button class="btn-primary" onclick="openModal('modal-add-product')">+ Add Product</button></div>
<div class="data-table"><table id="prod-table"><thead><tr><th>Name</th><th>Category</th><th>Supplier</th><th>Price</th><th>Stock</th><th>Status</th><th>Action</th></tr></thead><tbody>
<% try(java.sql.Connection con=com.store.util.DBConnection.getConnection(); java.sql.Statement st=con.createStatement(); java.sql.ResultSet rs=st.executeQuery("SELECT * FROM products ORDER BY id DESC")){ while(rs.next()){ int q=rs.getInt("quantity"); String cls=q<=0?"stock-red":(q<=5?"stock-yellow":"stock-green"); %>
<tr><td><%=rs.getString("name")%></td><td><%=rs.getString("category")%></td><td><%=rs.getString("supplier")%></td><td>₹<%=rs.getBigDecimal("price")%></td><td><span class="stock-badge <%=cls%>"><%=q%></span></td><td><%=rs.getString("status")%></td><td><a class="action-link delete" href="products?delete=<%=rs.getInt("id")%>" onclick="return confirm('Delete this product?')">Delete</a></td></tr>
<% }} catch(Exception e){ %><tr><td colspan="7" class="empty-state">Error: <%=e.getMessage()%></td></tr><% } %>
</tbody></table></div>
<div class="modal-overlay" id="modal-add-product"><div class="modal-box"><div class="modal-title">Add New Product</div><form action="products" method="post"><div class="form-group"><label>Name</label><input class="form-control" name="name" required></div><div class="form-group"><label>Description</label><textarea class="form-control textarea" name="description"></textarea></div><div class="form-group"><label>Price</label><input class="form-control" type="number" step="0.01" name="price" required></div><div class="form-group"><label>Stock</label><input class="form-control" type="number" name="stock" required></div><div class="form-group"><label>Category</label><select class="form-control" name="category"><% try(java.sql.Connection con=com.store.util.DBConnection.getConnection(); java.sql.Statement st=con.createStatement(); java.sql.ResultSet rs=st.executeQuery("SELECT category_name FROM categories ORDER BY category_name")){ while(rs.next()){ %><option><%=rs.getString(1)%></option><% }} catch(Exception e){} %></select></div><div class="form-group"><label>Supplier</label><select class="form-control" name="supplier"><% try(java.sql.Connection con=com.store.util.DBConnection.getConnection(); java.sql.Statement st=con.createStatement(); java.sql.ResultSet rs=st.executeQuery("SELECT name FROM suppliers ORDER BY name")){ while(rs.next()){ %><option><%=rs.getString(1)%></option><% }} catch(Exception e){} %></select></div><div class="modal-actions"><button type="button" class="btn-secondary" onclick="closeModal('modal-add-product')">Cancel</button><button class="btn-primary">Add Product</button></div></form></div></div>
</main></div></body></html>
